_target_: src.detector.pu.VanillaPU

model_type: ${model_type}
dataset_name: ${dataset_name}
novel_cls: ${novel_cls}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
oracle: ${oracle}
max_epochs: ${max_epochs}
constrained_penalty: ${constrained_penalty}
seed: ${seed}