_target_: src.detector.pu.VanillaPU

model_type: ${model_type}
dataset_name: ${dataset_name}
num_src_cls: ${num_src_cls}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
max_epochs: ${max_epochs}
constrained_penalty: ${constrained_penalty}
seed: ${seed}