_target_: src.detector.sar_em.SAREM

model_type: ${model_type}
arch_param: ${arch_param}
dataset_name: ${dataset_name}
novel_cls: ${novel_cls}
learning_rate: ${learning_rate}
weight_decay: ${weight_decay}
max_epochs: ${max_epochs}
inner_epochs: ${inner_epochs}
refit: ${refit}
seed: ${seed}